### ISSUE TITLE
Provide up to date builds / download links

### ISSUE THREAD

**Issue by Uninen** [boinx/QCJSON#3]
It seems that this project (and the Lua patch) isn't very actively maintained (PR:s open from 4 years ago) but it would be really nice to have up to date release builds (and maybe even a version number). 

There is currently two pages for information about these plugins (both for Lua and JSON): http://docs.boinxtv.com/json_patch and https://docs.mimo.live/docs/custom-layers 

The official documentation doesn't link to any up to date build but I suspect this here is at least newer version than the one this repo offers: http://cdn.boinx.com/software/qcplugins/JSON-Patch.zip

Thanks for the open source plugin -- hope you'll get the mimoLive documentation and the build up to date! 👍

**Comment by achimb** [comment]
Thanks for bringing this to our attention! I updated some plugins releases as well as the links to documentation in https://doc.mimo.live/
